spring:
  application:
    name: STOCK-PRICE-API

  datasource:
    url: jdbc:h2:mem:testDB
    username: SA
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    defer-datasource-initialization: true   # ✅ Required to fix your error

  h2:
    console:
      enabled: true

server:
  port: 1111

management:
  endpoints:
    web:
      exposure:
        include: '*'

