insert into STOCK_PRICE_DTLS (STOCK_PRICE_ID, COMPANY_NAME, COMPANY_STOCK_PRICE) values( 101,'SBI',430.00);
insert into STOCK_PRICE_DTLS (STOCK_PRICE_ID, COMPANY_NAME, COMPANY_STOCK_PRICE) values( 102,'ICICI',560.00);
insert into STOCK_PRICE_DTLS (STOCK_PRICE_ID, COMPANY_NAME, COMPANY_STOCK_PRICE) values( 10,'ADANI LTD',590.00);
insert into STOCK_PRICE_DTLS (STOCK_PRICE_ID, COMPANY_NAME, COMPANY_STOCK_PRICE) values( 104,'RELIANCE',1240.00);
insert into STOCK_PRICE_DTLS (STOCK_PRICE_ID, COMPANY_NAME, COMPANY_STOCK_PRICE) values( 105,'HDFC',1200.00);
insert into STOCK_PRICE_DTLS (STOCK_PRICE_ID, COMPANY_NAME, COMPANY_STOCK_PRICE) values( 106,'MRF',2000.00);